import Head from "next/head";
import NavBar from "./NavBar";

export default function PageLayout({ children, title = "Cublix" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#404040"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container relative min-w-full min-h-screen bg-zinc-900">
        <NavBar></NavBar>
        <main>{children}</main>
        <footer>
          <span className="flex justify-center">hola</span>
        </footer>
      </div>
    </>
  );
}
